# Use this Dockerfile when copying pre-built files to the Pi
# (no need for node or npm on the Pi)
FROM nginx:alpine
COPY dist/ /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
