"""
NFL Betting Lines Extractor
Pulls spread and over/under lines from nflverse and writes src/data/odds.js.

The output stores each team's line from their own perspective:
  spread < 0  →  team is favored
  spread > 0  →  team is the underdog

At runtime, the app computes:
  covered   = (teamScore - oppScore) + spread > 0
  wentOver  = (teamScore + oppScore) > total
  (Both scores are derived from scheduleMap, which already has ptsAgainst per team/week.)

Usage:
    pip install nflreadpy
    python scripts/extract_odds.py            # defaults to 2025 season
    python scripts/extract_odds.py 2025 2026  # multiple seasons
"""

import sys
from pathlib import Path

try:
    import nflreadpy
except ImportError:
    print("nflreadpy not found. Install with:  pip install nflreadpy")
    sys.exit(1)

# nflverse uses 'LA' for the Rams; our app uses 'LAR'
TEAM_MAP = {'LA': 'LAR'}

def map_team(t):
    return TEAM_MAP.get(t, t) if t else t

def extract_season(season: int) -> dict:
    """Return { week: { team: { spread, total } } } for one season."""
    print(f"  Loading {season} NFL schedules from nflverse...")
    df = nflreadpy.load_schedules([season])

    # nflreadpy returns a Polars DataFrame; convert to plain dicts
    cols = ['week', 'home_team', 'away_team', 'spread_line', 'total_line']
    try:
        rows = df.select(cols).to_dicts()          # Polars
    except AttributeError:
        rows = df[cols].to_dict(orient='records')  # pandas fallback

    odds_by_week = {}
    games_with_odds = 0

    for row in rows:
        week = row.get('week')
        if week is None:
            continue
        week = int(week)
        # Only regular season (weeks 1-18); heatmap doesn't render playoff weeks
        if week < 1 or week > 18:
            continue

        spread = row.get('spread_line')
        total  = row.get('total_line')
        if spread is None or total is None:
            continue
        try:
            spread = float(spread)
            total  = float(total)
        except (TypeError, ValueError):
            continue

        home = map_team(row.get('home_team'))
        away = map_team(row.get('away_team'))
        if not home or not away:
            continue

        if week not in odds_by_week:
            odds_by_week[week] = {}

        # spread_line in nflverse is the home team's line (positive = home favored).
        # We negate to get standard "negative = favored" convention from each team's perspective.
        odds_by_week[week][home] = {'spread': round(-spread, 1), 'total': round(total, 1)}
        odds_by_week[week][away] = {'spread': round(spread, 1),  'total': round(total, 1)}
        games_with_odds += 1

    print(f"  ✓ {games_with_odds} games with odds data across {len(odds_by_week)} weeks")
    return dict(sorted(odds_by_week.items()))


def build_js(seasons_data: dict) -> str:
    lines = [
        '// Auto-generated by scripts/extract_odds.py',
        '// Source: nflverse load_schedules()',
        '//',
        '// spread: negative = team is favored, positive = underdog (from that team\'s perspective)',
        '// total:  over/under total for the game',
        '//',
        '// Cover check:    (teamScore - oppScore) + spread > 0',
        '// Over/under:     teamScore + oppScore > total',
        '// (Scores come from scheduleMap which has ptsAgainst per team/week.)',
        '//',
        '// Re-run scripts/extract_odds.py to refresh.',
        '',
        'export const NFL_ODDS = {',
    ]

    for season in sorted(seasons_data):
        lines.append(f'  {season}: {{')
        for week in sorted(seasons_data[season]):
            lines.append(f'    {week}: {{')
            for team in sorted(seasons_data[season][week]):
                entry = seasons_data[season][week][team]
                lines.append(f'      {team}: {{ spread: {entry["spread"]}, total: {entry["total"]} }},')
            lines.append('    },')
        lines.append('  },')

    lines.append('};')
    lines.append('')
    return '\n'.join(lines)


def main():
    years = [int(y) for y in sys.argv[1:]] if len(sys.argv) > 1 else [2025]

    print(f"Extracting odds for season(s): {years}")
    seasons_data = {}
    for year in years:
        seasons_data[year] = extract_season(year)

    out_path = Path(__file__).parent.parent / 'src' / 'data' / 'odds.js'
    out_path.write_text(build_js(seasons_data))
    print(f"\n✓ Written to {out_path}")


if __name__ == '__main__':
    main()
